Repository quizk/quizk, pull requests merged in 2022-05, with the labels that each got.

#3 Adding `.github` folder for `quizk`
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/ISSUE_TEMPLATE/--feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: workspace enhancement

#6 Add breadcrumb
  Gemfile
  Gemfile.lock
  app/views/layouts/ops/_header.html.slim
  app/views/ops/operators/edit.html.slim
  app/views/ops/operators/index.html.slim
  app/views/ops/operators/new.html.slim
  app/views/ops/operators/show.html.slim
  config/application.rb
  config/breadcrumbs/ops.rb
  config/initializers/i18n.rb
  config/locales/en.yml
Labels: enhancement, back-end, size/L

#7 Dropdown on Avatar
  .gitignore
  app/assets/stylesheets/jet-theme/_style.bundle.css
  app/javascript/application.js
  app/javascript/jet-theme/scripts.bundle.js
  app/models/operator.rb
  app/views/layouts/ops/_header.html.slim
  config/importmap.rb
Labels: enhancement, back-end, size/XXL

#8 CRUD on Universities
  Gemfile
  app/controllers/concerns/ops/error_handler.rb
  app/controllers/ops/home_controller.rb
  app/controllers/ops/operators_controller.rb
  app/controllers/ops/universities_controller.rb
  app/models/university.rb
  app/views/layouts/ops/_sidebar.html.slim
  app/views/ops/operators/show.html.slim
  app/views/ops/universities/_form.html.slim
  app/views/ops/universities/edit.html.slim
  app/views/ops/universities/index.html.slim
  app/views/ops/universities/new.html.slim
  app/views/ops/universities/show.html.slim
  config/breadcrumbs/ops.rb
  config/routes/ops.rb
  db/migrate/20220522100629_create_universities.rb
  db/schema.rb
  lib/tasks/auto_annotate_models.rake
Labels: enhancement, back-end, size/L

#9 Using I18n
  app/assets/images/public/logo.jpg
  app/models/university.rb
  app/views/layouts/ops/_sidebar.html.slim
  app/views/ops/operators/_form.html.slim
  app/views/ops/operators/edit.html.slim
  app/views/ops/operators/index.html.slim
  app/views/ops/operators/new.html.slim
  app/views/ops/operators/show.html.slim
  app/views/ops/universities/_form.html.slim
  app/views/ops/universities/edit.html.slim
  app/views/ops/universities/index.html.slim
  app/views/ops/universities/new.html.slim
  app/views/ops/universities/show.html.slim
  config/breadcrumbs/ops.rb
  config/locales/breadcrumbs.en.yml
  config/locales/en.yml
  config/locales/flashes.en.yml
  config/locales/models/operator/en.yml
  config/locales/models/university/en.yml
  config/locales/views/ops/operators/en.yml
  config/locales/views/ops/universities/en.yml
Labels: enhancement, back-end, size/L

#13 works
  app/controllers/ops/categories_controller.rb
  app/controllers/ops/questions_controller.rb
  app/controllers/ops/topics_controller.rb
  app/models/question.rb
  app/models/topic.rb
  app/views/layouts/ops/_sidebar.html.slim
  app/views/ops/categories/show.html.slim
  app/views/ops/questions/_form.html.slim
  app/views/ops/questions/show.html.slim
  app/views/ops/topics/_form.html.slim
  app/views/ops/topics/edit.html.slim
  app/views/ops/topics/index.html.slim
  app/views/ops/topics/new.html.slim
  app/views/ops/topics/show.html.slim
  config/breadcrumbs/ops.rb
  config/locales/breadcrumbs.en.yml
  config/locales/models/topic/en.yml
  config/locales/sidebar.en.yml
  config/locales/views/ops/categories/en.yml
  config/locales/views/ops/questions/en.yml
  config/locales/views/ops/topics/en.yml
  config/routes/ops.rb
  db/migrate/20220524153218_create_categories.rb
  db/migrate/20220524153218_create_topics.rb
  db/migrate/20220524162425_create_questions.rb
  db/schema.rb
Labels: enhancement, back-end, size/L
